[package]
name = "mutagen-core"
version = "0.2.0"
authors = ["Samuel Pilz <samuel.pilz@posteo.net>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
proc-macro2 = { version = "0.4.28", features = ["span-locations"] }
failure = "0.1"
json = "0.11"
