[package]
name = "cargo-mutagen"
version = "0.2.0"
edition = "2018"

[dependencies]
json = "0.11"
failure = "0.1"
wait-timeout = "0.1.5"
mutagen = { path = "../mutagen"}
serde_json = "1.0"

[badges]
travis-ci = { repository = "llogiq/mutagen", branch = "master" }
